### ISSUE TITLE
Can't iterate to perform multiple snake games

### ISSUE THREAD

**Issue by MikeSchoenhals** [motiwari/Snake#18]
I'll be working to fix this as it's stalling my progress, but the following code won't work:

```
for i in range(5):
        theApp = App(args)
        theApp.on_execute()
```
If you quickly try running it, you'll see that the game doesn't reset. Not sure how to fix this.

**Comment by MikeSchoenhals** [comment]
This is needed to do a bunch of training. I'm to the point where I need to test my algorithm more to get the training to work.

**Comment by motiwari** [comment]
For now, we'll rerun multiple times with a powershell script on windows and a bash script on linux.

Powershell:
`for ($i=1; $i -le 10; $i++) {python play_game -v -a}`

Bash:
`X=0
while [ $X -le 20 ]
do
	python play_game.py -a -v
	X=$((X+1))
done`
