### ISSUE TITLE
Issues with data 

### ISSUE THREAD

**Issue by MikeSchoenhals** [motiwari/Snake#23]
Here are some general examples on output i'm getting. some of it is incorrect and it's difficult to say how much our results are affected by this type of thing: The head is the number '2' and the rest of the body are represented by the number '1'. The apple is the number 8. You can see that the direction is wrong. This happens quite frequently.

state number:  1
Old State:
 [[2 0 0 0]
 [0 0 0 0]
 [0 0 0 8]
 [0 0 0 0]]
Direction 3
Reward 3
New State:
 [[1 2 0 0]
 [0 0 0 0]
 [0 0 0 8]
 [0 0 0 0]]

Another case:
Old State:
 [[0 0 0 0]
 [1 0 8 0]
 [1 0 0 0]
 [2 0 0 0]]
Direction 3
Reward -98
New State:
 [[0 0 0 0]
 [0 0 8 0]
 [1 0 0 0]
 [1 0 0 0]]

**Comment by MikeSchoenhals** [comment]
This like this are happening frequently enough to where it will cause serious issues in training.

**Comment by motiwari** [comment]
Fixed in the solution to #17
